### ISSUE TITLE
Diseño de mockup de la interfaz:

### ISSUE THREAD

**Issue by 30225** [ISCOUTB/AH-YaperGoUTB#1]
Crear un diseño orientado a la experiencia del
usuario Web y Mobil - Responsable Daniel Isaias Cruz Gonzales

**Comment by iCruzDaniel** [comment]
![Image](https://github.com/user-attachments/assets/b21002f7-f276-475b-8939-b902243a1eb2)
Primera Vista Admin. YaperGO-UTB

![Image](https://github.com/user-attachments/assets/87cbd2f7-4f43-49da-8022-f9e50f894c53)
Primera Vista Estudiante YaperGO-UTB

**Comment by iCruzDaniel** [comment]
![Image](https://github.com/user-attachments/assets/7f377b82-8bae-47d2-bfb2-d49be710491f)
Vista Login Desktop

**Comment by iCruzDaniel** [comment]
![Image](https://github.com/user-attachments/assets/66b394b3-98f8-473b-a77b-14ff41e7e69b)
![Image](https://github.com/user-attachments/assets/72624acf-ba31-409c-86df-b119c5259f93)
![Image](https://github.com/user-attachments/assets/ab96bce8-513b-4dbc-b357-dc0b7105907f)
![Image](https://github.com/user-attachments/assets/10ba07d8-6298-4931-b137-232d1f9a129b)

Vistas de Móbil: Login, Usuario, Usuario_Menú, Usuario_Herramienta_calendario

**Comment by jairoserrano** [comment]
Adelante
