### ISSUE TITLE
Selección framework para el desarrollo de las API's

### ISSUE THREAD

**Issue by jesuMiranda** [ISCOUTB/AH-YaperGoUTB#14]
Selección de un framework para el desarrollo de las API's  para la base de datos

**Comment by 30225** [comment]
---

### Flexibilidad

Es fácil integrar **FastAPI** con otras tecnologías y servicios, lo que permite agregar funcionalidades como autenticación, bases de datos, y más, de manera sencilla.

### Sintaxis moderna

Aprovecha las características modernas de Python 3.6+ como anotaciones de tipo, lo que hace que el código sea más legible y mantenible.

### Respuesta rápida

**FastAPI** está construido sobre **Starlette** y utiliza **Uvicorn** como servidor ASGI, lo que permite manejar solicitudes de manera asíncrona y eficiente.

---

**Comment by jairoserrano** [comment]
Ok, Adelante
