### ISSUE TITLE
Selección de framework FrontEnd

### ISSUE THREAD

**Issue by 30225** [ISCOUTB/AH-YaperGoUTB#2]
Seleccionar un framework actualizado y que nos permita modularizar el desarrollo de la aplicación.

**Comment by iCruzDaniel** [comment]
![Image](https://github.com/user-attachments/assets/f410cd3e-4a2e-461d-9403-af4f3d183269)

Vue.js 3 es una excelente opción por:

Rendimiento: Utiliza la compilación Ahead-of-Time (AOT), lo que resulta en un código más rápido y eficiente.
Flexibilidad: La Composition API permite una mayor organización y reutilización del código.
Tipo seguro: El soporte nativo para TypeScript mejora la calidad del código.
Tamaño reducido: Vue 3 tiene un tamaño de paquete más pequeño, lo que mejora el tiempo de carga de las aplicaciones.
Comunidad activa: Cuenta con una gran comunidad y una amplia documentación.

**Comment by jairoserrano** [comment]
Adelante
