### ISSUE TITLE
Pruebas de usabilidad: 

### ISSUE THREAD

**Issue by 30225** [ISCOUTB/AH-YaperGoUTB#4]
pruebas deben ser realizadas previo a la puesta en operación
del software, donde se compruebe la integridad y funcionalidad del mismo, seguridad
de los datos, entre otros. Responsable: Jesús David Miranda Mercado

**Comment by jesuMiranda** [comment]
Pruebas de usabilidad del proyecto y comprobadas con SonarCloud realizadas
