### ISSUE TITLE
Seleccionar Motor Base de Datos

### ISSUE THREAD

**Issue by iCruzDaniel** [ISCOUTB/AH-YaperGoUTB#6]
Elegir un Motor de Base Datos para el modelo de datos diseñado

**Comment by iCruzDaniel** [comment]
Guiándonos por el teorema de _CAP_, el _SGBD_ escogido es **MySQL**. Ya que es un sistema posee una alta consistencia y disponibilidad de los datos, características super importantes para la aplicación que estamos desarrollando. También, para el volumen de datos que se va a manejar es más que suficiente y además es de código abierto.

**Comment by jairoserrano** [comment]
Seleccionado entonces. procedan a buscar qué imágenes y versiones de docker les funcionará.
