### ISSUE TITLE
Definir modelo de datos (Diagrama ER)

### ISSUE THREAD

**Issue by iCruzDaniel** [ISCOUTB/AH-YaperGoUTB#9]

**Comment by iCruzDaniel** [comment]
Desarrollar con un diagrama ER el modelo de Datos

**Comment by iCruzDaniel** [comment]
![Image](https://github.com/user-attachments/assets/66900342-7d6f-45e3-948b-7b4b46197900)

Diagrama ER para la base de Datos

**Comment by jairoserrano** [comment]
adelante
